# Generated by Django 4.2 on 2023-07-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enquiry_source', models.CharField(choices=[('youtube', 'YOUTUBE'), ('instagram', 'INSTAGRAM')], default='youtube', max_length=100)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Student', models.CharField(max_length=20, null=True)),
                ('Email', models.EmailField(max_length=20, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Dob', models.DateField(null=True)),
                ('Street', models.CharField(max_length=20, null=True)),
                ('State', models.CharField(choices=[('kerala', 'KERALA'), ('karnataka', 'KARNATAKA'), ('nagaland', 'NAGALAND'), ('tamilnadu', 'TAMILNADU'), ('rajasthan', 'RAJASTHAN'), ('punjab', 'PUNJAB')], max_length=20)),
                ('Pincode', models.CharField(max_length=20, null=True)),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20)),
                ('Alternative_Email', models.EmailField(max_length=20, null=True)),
                ('Alternative_address', models.CharField(max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=20, null=True)),
                ('City', models.CharField(max_length=20, null=True)),
                ('District', models.CharField(choices=[('kasargod', 'KASARGOD'), ('kannur', 'KANNUR'), ('kozhikkode', 'KOZHKKODE'), ('wayanad', 'WAYANAD'), ('malappuram', 'MLAPPURAM'), ('palakkad', 'PALAKKAD')], max_length=20)),
                ('Whatsapp', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'students',
            },
        ),
    ]
