# Generated by Django 4.2 on 2023-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_students_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='State',
            field=models.CharField(choices=[('kerala', 'KERALA'), ('karnataka', 'KARNATAKA'), ('tamilnadu', 'TAMILNADU'), ('rajasthan', 'RAJASTHAN')], max_length=20),
        ),
    ]
