# Generated by Django 4.2.2 on 2023-07-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow_up_statuses',
            options={'verbose_name': 'follow up status', 'verbose_name_plural': 'Follow up statuses'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='street',
        ),
        migrations.AlterField(
            model_name='batch',
            name='Course',
            field=models.CharField(choices=[('python django', 'PYTHON DJANGO'), ('mean stack', 'MEAN STACK'), ('digital marketing', 'DIGITAL MARKETING')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='Trainer',
            field=models.CharField(choices=[('radhika', 'RADHIKA'), ('rohini', 'ROHINI')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.district'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.state'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='districtname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry_source',
            name='enquirysourcename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='follow_up_statuses',
            name='Followupstatusname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_data',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_data',
            name='Type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='master_data',
            name='Value',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='Qualificationname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='statename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
