# Generated by Django 4.2 on 2023-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_follow_up_statuses_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='state',
            field=models.CharField(choices=[('kerala', 'KERALA'), ('karnataka', 'KARNATAKA')], max_length=10),
        ),
    ]
